-- KANEKI STORE + SUPABASE
-- Execute este arquivo inteiro no Supabase Dashboard > SQL Editor.
-- O backend da KANEKI usa a conexão PostgreSQL do Supabase e faz as operações administrativas no servidor.

create extension if not exists pgcrypto;

create table if not exists public.users (
  id text primary key,
  email text unique not null,
  name text not null,
  phone text default '',
  password_hash text,
  role text not null default 'customer' check (role in ('customer','admin','owner')),
  provider text not null default 'password',
  avatar_url text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.carts (
  user_id text primary key references public.users(id) on delete cascade,
  cart jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  product_id text primary key,
  name text not null,
  description text not null default '',
  price numeric not null,
  old_price numeric not null default 0,
  stock text not null default '0',
  image text not null default '',
  catalog text not null default 'produtos',
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id text references public.users(id) on delete set null,
  order_key text unique not null,
  items jsonb not null,
  total numeric not null,
  name text,
  email text,
  phone text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  user_id text references public.users(id) on delete cascade,
  order_id bigint references public.orders(id) on delete cascade,
  subject text not null,
  status text not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ticket_messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint references public.tickets(id) on delete cascade,
  sender_role text not null,
  name text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  action text not null,
  email text,
  at timestamptz not null default now()
);

create table if not exists public.pix_orders (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete set null,
  order_key text unique not null,
  qr_code_id text unique not null,
  amount numeric not null,
  status text not null default 'PENDING',
  nick text default '',
  expires_at timestamptz,
  asaas_payment_id text,
  event_id text unique,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create table if not exists public.pix_orders_event_guard (
  event_id text primary key,
  received_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id text references public.users(id) on delete set null,
  name text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  user_id text references public.users(id) on delete set null,
  order_id bigint references public.orders(id) on delete set null,
  rating int not null check (rating between 1 and 5),
  message text not null,
  product_text text not null default '',
  created_at timestamptz not null default now(),
  unique(user_id,order_id)
);

-- Garante o dono da aplicação.
insert into public.users(id,email,name,role,provider)
values ('owner-administradorsupreme','administradorsupreme@gmail.com','KANEKI OWNER','owner','google')
on conflict(email) do update set role='owner', provider='google';

-- Configurações básicas usadas pelo site.
insert into public.site_settings(key,value) values
('siteName','KANEKI STORE'),
('pixFee','1.49'),
('whatsappNumber','5591985748541'),
('primaryColor','#e21b23'),
('primaryDark','#b91c1c'),
('backgroundColor','#070707'),
('cardColor','#111111')
on conflict(key) do nothing;

-- Storage público para imagens do site.
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values (
  'kaneki-assets',
  'kaneki-assets',
  true,
  10485760,
  array['image/png','image/jpeg','image/webp','image/gif','video/mp4','video/webm']
)
on conflict (id) do update set
  public=true,
  file_size_limit=10485760,
  allowed_mime_types=excluded.allowed_mime_types;

-- As tabelas abaixo são acessadas pelo backend confiável, não diretamente pelo navegador.
-- Por isso RLS fica habilitado e sem políticas públicas permissivas.
alter table public.users enable row level security;
alter table public.carts enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.tickets enable row level security;
alter table public.ticket_messages enable row level security;
alter table public.logs enable row level security;
alter table public.pix_orders enable row level security;
alter table public.pix_orders_event_guard enable row level security;
alter table public.chat_messages enable row level security;
alter table public.site_settings enable row level security;
alter table public.reviews enable row level security;

-- Storage: leitura pública para as imagens publicadas.
drop policy if exists "kaneki assets public read" on storage.objects;
create policy "kaneki assets public read"
on storage.objects for select
using (bucket_id='kaneki-assets');

-- Upload/alteração/exclusão são feitos pelo backend com a service role.
-- A service role não deve ser colocada no HTML/JavaScript do navegador.

-- Índices úteis.
create index if not exists products_catalog_active_idx on public.products(catalog,active);
create index if not exists orders_user_idx on public.orders(user_id,created_at desc);
create index if not exists tickets_user_idx on public.tickets(user_id,updated_at desc);
create index if not exists chat_created_idx on public.chat_messages(created_at desc);
create index if not exists logs_at_idx on public.logs(at desc);

-- Recarrega o cache do PostgREST depois da criação das estruturas.
notify pgrst, 'reload schema';
